### ISSUE TITLE
Manually assign txid for a tx request?

### ISSUE THREAD

**Issue by charlesjhongc** [starkware-industries/starkex-clientlib-js#9]
Hi, we're trying to integrate starkex and seems like txid of a gateway request in this lib is assigned automatically and internally within the gateway class. By this design, caller is not aware of the txid, so there's no way to trace it's status. Do I misunderstand the way how this api should be used? Or is it possible that allowing caller bring in the txid along with request body?

**Comment by dan-ziv** [comment]
Hi @charlesjhongc and thanks for reporting this issue!

We're working on a fix in which we will return the selected `txId` in the response.
This will be done hopefully by the end of the week.

Later on, we will add another feature that will allow adding a custom `txId` in the request itself.

**Comment by dan-ziv** [comment]
Fix has been merged to master

**Comment by charlesjhongc** [comment]
Thanks 😄
